config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'homes#index'

  resources :homes, only: :index

  namespace :admins do
    namespace :articles do
      post 'csv_upload'
    end

    resources :articles do
      resources :comments
    end

    resources :catagories do
      resources :product_catagories
    end

    resources :articles do
      member do
        delete :delete_image
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :articles, only: [] do
        resources :comments, only: :index
      end
    end
  end
end

app/models/catagory.rb
class Catagory < ApplicationRecord
    has_many :product_catagory
    has_many :article, through: :product_catagory
end

app/controllers/admins/catagories_controller.rb
class Admins::CatagoriesController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :new, :create, :update, :destroy]
  def index
    @search = params[:search]

    @catagories = Catagory.all
    @catagories = @catagories
      .where("title LIKE ? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
    @catagories = @catagories.page(params[:page]).per(5)
  end

  def show
    @catagory = Catagory.find(params[:id])
  end

  def new
    puts "This is how you print out something."
    @catagory = Catagory.new
  end

  def edit
    @catagory = Catagory.find(params[:id])
  end

  def create
    @catagory = Catagory.create(catagory_params)

    if @catagory.invalid?
      flash[:error] = @catagory.errors.full_messages
    end

    redirect_to action: :index
  end

  def update
    @catagory = Catagory.find(params[:id])
    @catagory.update(catagory_params)
    redirect_to action: :index
  end

  def destroy
    @catagory = Catagory.find(params[:id])
    @catagory.destroy
    redirect_to action: :index
  end

  private

  def catagory_params
    params.require(:catagory).permit(:title, :body)
  end
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :new, :create, :update, :destroy]
  def index
    @search = params[:search]

    @catagories = Catagory.all
    @catagories = @catagories
      .where("title LIKE ? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
    @catagories = @catagories.page(params[:page]).per(5)
  end

  def show
    @catagory = Catagory.find(params[:id])
  end

  def new
    puts "This is how you print out something."
    @catagory = Catagory.new
  end

  def edit
    @catagory = Catagory.find(params[:id])
  end

  def create
    @catagory = Catagory.create(catagory_params)

    if @catagory.invalid?
      flash[:error] = @catagory.errors.full_messages
    end

    redirect_to action: :index
  end

  def update
    @catagory = Catagory.find(params[:id])
    @catagory.update(catagory_params)
    redirect_to action: :index
  end

  def destroy
    @catagory = Catagory.find(params[:id])
    @catagory.destroy
    redirect_to action: :index
  end

  private

  def catagory_params
    params.require(:catagory).permit(:title, :body)
  end
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/views/admins/catagories/_form.slim
= form_with model: [:admins, catagory] do |f|
  div = f.text_field :title, placeholder: 'Title'
  br
  div = f.text_area :body, placeholder: 'Write content here'
  br
  div = f.submit 'Submit Catagory'

app/views/admins/catagories/edit.slim
h1 Edit catagory

div = link_to 'Back', admins_catagories_path
br
= render 'form', catagory: @catagory

app/views/admins/catagories/index.slim
.row
  .col-6
    h1 Catagory list
  .col-6
    -if current_admin
      .float-right
        span.ml-3 = current_admin.email
        span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
        span.ml-3 = link_to 'Logout', destroy_admin_session_path , method: :delete
    -else
      .float-right
        span.ml-2 = link_to 'Login', admin_session_path

.row
  .col
    = form_tag admins_catagories_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something',
        class: 'form-control'

.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Title
          th Body
          th Created at
          th Updated at
          th Action
      tbody
        - @catagories.each do |a|
          tr
            td = a.id
            td.font-weight-bold = a.title
            td = a.body
            td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
            td
              span
                = link_to admins_catagory_path(a) do
                  i.fas.fa-eye
              -if current_admin
                span.ml-3
                  = link_to edit_admins_catagory_path(a) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to admins_catagory_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                    i.fas.fa-trash

.row
  .col-6
    = paginate @catagories
  .col-6 
    .float-right
      span.ml-3
        = link_to admins_articles_path do
          = button_tag 'Product', class: 'btn btn-primary'
      -if current_admin
        span.ml-3
          = link_to new_admins_catagory_path do
            = button_tag 'Add new Catagory', class: 'btn btn-primary'

app/views/admins/catagories/new.slim
h1 Add new catagory

div = link_to 'Back', admins_catagories_path
br
= render 'form', catagory: @catagory

app/views/admins/catagories/show.slim
h1 = @catagory.title
div = link_to 'Back', admins_catagories_path
hr
div = @catagory.body
hr
h2 Article Section
div
  - @catagory.article.each do |article|
    div = link_to  "#{article.title}", admins_article_path(article)

-if current_admin
  = form_with model: [:admins, @catagory, @catagory.product_catagory.build] do |f|
      div = f.collection_select :result, Article.all, :body,:title
      div = f.submit 'Submit'