config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'homes#index'

  resources :homes, only: :index

  namespace :admins do
    namespace :articles do
      post 'csv_upload'
    end

    resources :articles do
      resources :comments
    end

    resources :catagories do
      resources :product_catagories
    end

    resources :articles do
      member do
        delete :delete_image
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :articles, only: [] do
        resources :comments, only: :index
      end
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  enum status: {draft: 0, published: 1, archived: 2}

  scope :search, -> (arg) {where("title LIKE ? or body LIKE ?", "%#{arg}%", "%#{arg}%")}

  has_many :comments
  has_many :product_catagory
  has_many :catagory, through: :product_catagory

  has_one_attached :single_image
  has_many_attached :multi_image

  validates :body, length: { minimum: 4 }
  validate :no_bad_words_in_title

  validates_numericality_of :stock, :price, :only_integer => true, :greater_than_or_equal_to => 0

  def no_bad_words_in_title
    if title.downcase.include?('bad')
      errors.add(:title, 'cannot contain bad words')
    end
  end

end

app/controllers/admins/articles_controller.rb
class Admins::ArticlesController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :new, :create, :update, :destroy]

  def index
    @search = params[:search]

    @articles = Article.all
    @articles = @articles.search(@search) if @search.present?
    @articles = @articles.page(params[:page]).per(5)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Article.all), file_name: 'articles.csv'}
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    puts "This is how you print out something."
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)

    if @article.invalid?
      flash[:error] = @article.errors.full_messages
    end

    redirect_to action: :index
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to action: :index
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to action: :index
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Article.create title: attr[0], body: attr[1]
    end
    redirect_to action: :index
  end

  def generate_csv(articles)
    articles.map{ |a| [a.title, a.body, a.created_at.to_date].join(',')}.join("\n")
  end

  def delete_image
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_to action: :index
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :stock, :price, :single_image, multi_image: [], :status => []).tap do |w|
      w[:status] = w[:status][1].to_i
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :new, :create, :update, :destroy]

  def index
    @search = params[:search]

    @articles = Article.all
    @articles = @articles.search(@search) if @search.present?
    @articles = @articles.page(params[:page]).per(5)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Article.all), file_name: 'articles.csv'}
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    puts "This is how you print out something."
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)

    if @article.invalid?
      flash[:error] = @article.errors.full_messages
    end

    redirect_to action: :index
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to action: :index
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to action: :index
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Article.create title: attr[0], body: attr[1]
    end
    redirect_to action: :index
  end

  def generate_csv(articles)
    articles.map{ |a| [a.title, a.body, a.created_at.to_date].join(',')}.join("\n")
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :stock, :price, :status => []).tap do |w|
      w[:status] = w[:status][1].to_i
    end
  end
end

app/views/admins/articles/_form.slim
= form_with model: [:admins, article] do |f|
  h2 Title
  div = f.text_field :title, placeholder: 'Title'
  br
  h2 Body
  div = f.text_area :body, placeholder: 'Write content here'
  br
  h2 Numbers of stock
  div = f.number_field :stock, placeholder: 'Number of stock'
  br
  h2 Price
  div = f.number_field :price, placeholder: 'Price'
  br
  h2 Status 
  div = f.collection_check_boxes :status, Article.statuses.map, :last, :first
  br

  h2 Main image
  - if @article.single_image.attached?
    div = link_to 'Remove', delete_image_admins_article_url(@article.single_image.id), method: :delete
  - else
    div = f.file_field :single_image
  br

  h2 Support image 
  - if @article.multi_image.attached?
    div = f.file_field :multi_image, multiple: true
  - else
    div = f.file_field :multi_image, multiple: true
  br
  div = f.submit 'Submit Article'

app/views/admins/articles/edit.slim
h1 Edit article

div = link_to 'Back', admins_articles_path
br
= render 'form', article: @article

app/views/admins/articles/index.slim
.row
  .col-6
    h1 Product list admin
  .col-6
    -if current_admin
      .float-right
        span.ml-3 = current_admin.email
        span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
        span.ml-3 = link_to 'Logout', destroy_admin_session_path , method: :delete
    -else
      .float-right
        span.ml-2 = link_to 'Login', admin_session_path 

.row
  .col-8
    = form_tag admins_articles_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something',
        class: 'form-control'
  .col
    = link_to admins_articles_path(format: :csv) do
      = button_tag 'Download CSV', class: 'btn btn-secondary float-right'
  .col
     = link_to homes_path do
      = button_tag 'Product show', class: 'btn btn-primary'
.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Title
          th Body
          th No. Comments
          th Stock
          th Price
          th Status
          th Image
          th Action
      tbody
        - @articles.each do |a|
          tr
            td = a.id
            td.font-weight-bold = a.title
            td = a.body
            td = a.comments.count
            td = a.stock
            td = a.price
            td = a.status.presence || 'NA'
            - if a.single_image.attached?
                td = image_tag a.single_image, style: 'width: 200px;'
            - else
                td = 'None' 
            td
              span
                = link_to admins_article_path(a) do
                  i.fas.fa-eye

              -if current_admin
                span.ml-3
                  = link_to edit_admins_article_path(a) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to admins_article_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                    i.fas.fa-trash

.row
  .col-6
    = paginate @articles
  .col-6 
    .float-right
      span.ml-3
        = link_to admins_catagories_path do
          = button_tag 'Catagory', class: 'btn btn-primary'
      -if current_admin
        span.ml-3
          = link_to new_admins_article_path do
            = button_tag 'Add new Article', class: 'btn btn-primary'

div
  hr

.row
  .col
    = form_tag admins_articles_csv_upload_path, multipart: true do
      div = file_field_tag :csv_file
      br
      div = submit_tag :upload

app/views/admins/articles/new.slim
h1 Add new article

div = link_to 'Back', admins_articles_path
br
= render 'form', article: @article

app/views/admins/articles/show.slim
h1 = @article.title
div = link_to 'Back', admins_articles_path
br
div = @article.body
br

h2 Main image 
- if @article.single_image.attached?
  = image_tag @article.single_image, style: 'width:300px'
- else 
  p None

h3 Support image 
- if @article.multi_image.attached?
  table
    tbody 
    - (0...@article.multi_image.count).each do |index|
      td
        div = image_tag @article.multi_image[index], style: 'height: 100px;'
        div
          = link_to 'Remove', delete_image_admins_article_url(@article.multi_image[index].id), method: :delete, style: 'text-align: center;'
- else
  p None

br
h2 Comments Section
div
  - @article.comments.each do |comment|
    div = "#{comment.author} Wrote : #{comment.text}"
br
h2 Add new Comment Section
= form_with model: [:admins, @article, @article.comments.build] do |f|
  div = f.text_field :author, placeholder: 'Author'
  div = f.text_area :text, placeholder: 'Write text here'
  div = f.submit 'Submit Comment'

app/views/admins/articles/user_index.slim
.row
  .col-6
    h1 Product list
  .col-6
    .float-right
      span.ml-3 = link_to 'Login', articles_admin_path

.row
  .col
    = form_tag admins_articles_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something',
        class: 'form-control'

.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Title
          th Body
          th No. Comments
          th Stock
          th Price
          th Status
          th Created at
          th Updated at
          
      tbody
        - @articles.each do |a|
          tr
            td = a.id
            td.font-weight-bold = a.title
            td = a.body
            td = a.comments.count
            td = a.stock
            td = a.price
            td = a.status.presence || 'NA' 
            td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
          
.row
  .col-6
    = paginate @articles